# Generated by Django 5.0.6 on 2024-11-18 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(upload_to='contratos/')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'contratoApp_login',
            },
        ),
        migrations.CreateModel(
            name='trabajadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('afp', models.CharField(max_length=50)),
                ('estado_civil', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('previcion_salud', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='trabajadores')),
                ('correo', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContratoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_termino', models.DateField()),
                ('ArchivoContrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratoApp.contrato')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratoApp.trabajadores')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='contratos_generados/')),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('contrato_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='contratoApp.contratotrabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('sueldo', models.IntegerField()),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('vigente', models.CharField(choices=[('Vigente', 'Vigente'), ('No vigente', 'No vigente')], default='Vigente', max_length=50)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratoApp.trabajadores')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('presente', models.BooleanField(default=False)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratoApp.trabajadores')),
            ],
        ),
        migrations.CreateModel(
            name='antecedentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratoApp.trabajadores')),
            ],
        ),
    ]
