# Generated by Django 5.0.6 on 2024-11-18 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='contratoApp.trabajadores'),
        ),
    ]
