# Generated by Django 5.0.6 on 2024-10-30 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratoApp', '0001_initial'),
    ]

    # Contrato ya se crea en 0001_initial. Esta migracion queda como puente
    # para resolver la rama historica duplicada sin intentar crear la tabla otra vez.
    operations = []
