# Generated by Django 5.0.6 on 2024-11-19 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratoApp', '0002_alter_cargo_trabajador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='trabajador',
        ),
        migrations.AddField(
            model_name='cargo',
            name='trabajadores',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contratoApp.trabajadores'),
            preserve_default=False,
        ),
    ]
