# Generated by Django 5.1.3 on 2024-11-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratoApp', '0003_remove_cargo_trabajador_cargo_trabajadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadores',
            name='sent',
            field=models.CharField(default='no_enviado', max_length=50),
        ),
    ]
