# Generated by Django 5.0.6 on 2026-09-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratoApp', '0002_contrato'),
        ('contratoApp', '0004_trabajadores_sent'),
    ]

    operations = [
    ]
